import aws_cdk as cdk
from aws_cdk.assertions import Match, Template

from infra.aws.earnings_monitor_stack import EarningsMonitorStack


def template(extra_context: dict | None = None) -> Template:
    context = {
            "container_image": "example.invalid/earnings-monitor:test",
            "schedule": "rate(15 minutes)",
    }
    context.update(extra_context or {})
    app = cdk.App(context=context)
    return Template.from_stack(EarningsMonitorStack(app, "TestEarningsMonitor"))


def test_core_resources_are_synthesized() -> None:
    stack = template()
    stack.resource_count_is("AWS::SQS::Queue", 2)
    stack.has_resource_properties("AWS::Lambda::Function", {"Handler": "dispatcher.handler"})
    stack.has_resource_properties("AWS::Lambda::Function", {"Handler": "poller.handler"})
    stack.resource_count_is("AWS::DynamoDB::Table", 1)
    stack.resource_count_is("AWS::S3::Bucket", 1)
    stack.resource_count_is("AWS::ECS::Service", 2)
    # Three operational alarms plus two generated by queue-depth step scaling.
    stack.resource_count_is("AWS::CloudWatch::Alarm", 5)


def test_schedule_and_dead_letter_queue_are_wired() -> None:
    stack = template()
    stack.has_resource_properties(
        "AWS::Events::Rule",
        {"ScheduleExpression": "rate(15 minutes)", "State": "ENABLED"},
    )
    stack.has_resource_properties(
        "AWS::SQS::Queue",
        {"RedrivePolicy": Match.object_like({"maxReceiveCount": 3})},
    )


def test_storage_is_not_public() -> None:
    stack = template()
    stack.has_resource_properties(
        "AWS::S3::Bucket",
        {
            "PublicAccessBlockConfiguration": {
                "BlockPublicAcls": True,
                "BlockPublicPolicy": True,
                "IgnorePublicAcls": True,
                "RestrictPublicBuckets": True,
            },
            "VersioningConfiguration": {"Status": "Enabled"},
        },
    )


def test_cognito_auth_can_be_enabled_without_lookups() -> None:
    stack = template(
        {
            "certificate_arn": "arn:aws:acm:us-east-1:123456789012:certificate/test",
            "cognito_user_pool_arn": "arn:aws:cognito-idp:us-east-1:123456789012:userpool/us-east-1_test",
            "cognito_user_pool_client_id": "testclient",
            "cognito_user_pool_domain": "test-domain",
        }
    )
    stack.has_resource_properties(
        "AWS::ElasticLoadBalancingV2::ListenerRule",
        {"Actions": Match.array_with([Match.object_like({"Type": "authenticate-cognito"})])},
    )
