NVDA:
  type: nvidia_fiscal
AMZN:
  type: calendar_fiscal
MSFT:
  type: offset_fiscal
  fye_month: 6
  fye_day: 30
AAPL:
  type: offset_fiscal
  fye_month: 9
  fye_day: 30
TSLA:
  type: calendar_fiscal

TXN:
  type: calendar_fiscal

CTSH:
  type: calendar_fiscal

SPCX:
  type: calendar_fiscal

