NVDA:
  type: nvidia_fiscal
AMZN:
  type: calendar_fiscal
MSFT:
  type: offset_fiscal
  fye_month: 6
  fye_day: 30
AAPL:
  type: offset_fiscal
  fye_month: 9
  fye_day: 30
TSLA:
  type: calendar_fiscal
TXN:
  type: calendar_fiscal
CTSH:
  type: calendar_fiscal
SPCX:
  type: calendar_fiscal
CSCO:
  type: offset_fiscal
  fye_month: 7
  fye_day: 31
STRW:
  type: calendar_fiscal
OPAL:
  type: calendar_fiscal
AMD:
  type: calendar_fiscal
ACN:
  type: offset_fiscal
  fye_month: 8
  fye_day: 31
ADBE:
  type: offset_fiscal
  fye_month: 11
  fye_day: 27
ADI:
  type: offset_fiscal
  fye_month: 11
  fye_day: 1
ADSK:
  type: offset_fiscal
  fye_month: 1
  fye_day: 31
AMAT:
  type: offset_fiscal
  fye_month: 10
  fye_day: 26
APH:
  type: calendar_fiscal
AVGO:
  type: offset_fiscal
  fye_month: 11
  fye_day: 1
CRM:
  type: offset_fiscal
  fye_month: 1
  fye_day: 31
IBM:
  type: calendar_fiscal
INTU:
  type: offset_fiscal
  fye_month: 7
  fye_day: 31
LRCX:
  type: offset_fiscal
  fye_month: 6
  fye_day: 28
MU:
  type: offset_fiscal
  fye_month: 9
  fye_day: 3
ORCL:
  type: offset_fiscal
  fye_month: 5
  fye_day: 31
TEL:
  type: offset_fiscal
  fye_month: 9
  fye_day: 25
LLY:
  type: calendar_fiscal
UNH:
  type: calendar_fiscal
MRK:
  type: calendar_fiscal
JNJ:
  type: offset_fiscal
  fye_month: 1
  fye_day: 3
ABBV:
  type: calendar_fiscal
TMO:
  type: calendar_fiscal
ABT:
  type: calendar_fiscal
PFE:
  type: calendar_fiscal
AMGN:
  type: calendar_fiscal
ISRG:
  type: calendar_fiscal
MDT:
  type: offset_fiscal
  fye_month: 4
  fye_day: 24
BMY:
  type: calendar_fiscal
REGN:
  type: calendar_fiscal
CI:
  type: calendar_fiscal
BSX:
  type: calendar_fiscal
DHR:
  type: calendar_fiscal
SYK:
  type: calendar_fiscal
GILD:
  type: calendar_fiscal
VRTX:
  type: calendar_fiscal
ELV:
  type: calendar_fiscal
CRWV:
  type: calendar_fiscal
DDOG:
  type: calendar_fiscal
LITE:
  type: offset_fiscal
  fye_month: 6
  fye_day: 30
