# -*- coding: utf-8 -*-
import json
from pathlib import Path
REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2022-Q4.json"
ROWS = [
    (3636.26, "Truong Nguyen", "Hi, guys. Thanks for the question. Truong Nguyen from Credit Suisse. Just a question on STELARA erosion expectations. I was hoping you can give us some thoughts about the cadence of biosimilar products that are gonna be coming along this year."),
    (3651.84, "Truong Nguyen", "None are approved yet, can we expect the first company to enter with exclusivity for six months, something we've seen with Humira and then the rest coming in 2024? Should we expect all the players to come at once? Any color on this patent dance would be helpful. Thanks."),
    (3669.44, "Joaquin Duato", "Thank you for the question. It's difficult for us to comment on your topics there. There's no approved biosimilars at this time, and we are going to continue to monitor the situation. As we have commented, we expect the erosion curve of STELARA to be likely deeper than that of Remicade, given the evolution of the biosimilar market and the fact that STELARA is a self-administered product. As well as potentially, to your point, potentially interchangeability in the label. That's how we see the STELARA loss of exclusivity. In 2023, when we think about STELARA in the U.S., we see the sales of STELARA flat to declining, obviously, given the price pressures that will be offset also by continuous volume growth that we see in Ste."),
    (3730.84, "Joaquin Duato", "That's the perspective that we have for STELARA in 2023. Overall, we have a very strong immunology franchise. I commented on TREMFYA before, the continuous progression in psoriasis and psoriatic arthritis, the readout of our ulcerative colitis and Crohn's disease studies, which is exciting. Also in 2023, we may have some data from our phase II study of our oral IL-23, which we think it's a very exciting, underappreciated opportunity in our pipeline too."),
    (3769.28, "Operator", "Thank you. Next question today is coming from Chris Shibutani from Goldman Sachs. Your line is now live."),
    (3775.48, "Chris Shibutani", "Thank you very much. The multiple myeloma franchise, obviously very central to your objective for 2025. Between the CAR T, sort of, gradual launch that you have based upon supply and the bispecifics, can you talk about what that interplay has been since the approval and launch and what you're expecting through the year in 2023? Thank you."),
    (3798.7, "Joaquin Duato", "As far as the demand for CARVYKTI, we see very strong demand for CARVYKTI and also for TECVAYLI. There's a significant need for new therapies in this relapsed refractory patient population. The demand for the products, the physicians, and patient adoption has been really strong. That is really encouraging and portends the unmet medical need for these type of patients. With CARVYKTI, we continue to scale our production capacity and expand our network of providers, and we are doing that in a phased approach. With TECVAYLI, we are off to a successful start, and the early indications for this of the self option are very positive too, connected with the high unmet medical need that we see there."),
    (3857.58, "Joaquin Duato", "Moving into 2023, key elements of that would be from a data perspective, the reading CARTITUDE-4, which would give us the opportunity to move CARVYKTI into earlier lines of therapy. Also the filing of talquetamab, which will give us another line of therapy because some of the studies of talquetamab are done in patients who have failed BCMA, either cell therapy or bispecifics, and the continuous data that we'll continue to provide to guide how to use this incredible portfolio in multiple myeloma."),
    (3895.4, "Operator", "Thank you. Next question."),
    (3896.84, "Jessica Moore", "Sorry. Sorry, Kevin. We have time for one last question."),
    (3901.64, "Operator", "Perfect. Our final question today is coming from Louise Chen from Cantor Fitzgerald. Your line is now live."),
    (3907.24, "Louise Chen", "Hi. Thank you for taking my question here. I wanted to ask you about the timing of data readouts, first half or second half, and your expectations for a few products. First one is Nipocalimab and rheumatoid arthritis, and then your oral IL-23. I saw that a trial was finished and what your next steps are here and when you might have some data. Lastly, just on your RYBREVANT and lazertinib, are you still expecting a potential year interim readout for lung cancer sphere? Thank you."),
    (3938.84, "Joaquin Duato", "Regarding the main data readouts that you could expect in 2023, I commented already on CARTITUDE-4, which is a key one for us. This is an event-driven study, so it's difficult for us to give you an exact timing, Louise. Importantly, we have the potential for an interim analysis of the MARIPOSA study, which is the study of RYBREVANT plus lazertinib in frontline non-small cell lung cancer with EGFR mutations. In this study, versus TAGRISSO. This is an important study for us. We have the potential clinical data from the PAPILLON study, which is in frontline non-small cell lung cancer in combination with chemotherapy. Those are, those are important ones in non-small cell lung cancer."),
    (3992.42, "Joaquin Duato", "Staying in oncology, we also have the data from the phase II SunRISe-1 study of our TAR-200 platform, our drug-eluting device in non-muscle invasive bladder cancer. We continue to work on our high risk localized prostate cancer with ERLEADA. That's key elements in our oncology side. As far as Nipocalimab, we are expecting data from our phase D studies in RA, in rheumatoid arthritis, which I know has created significant attention from you and also in hemolytic disease of the fetus and the newborn. It will be towards the later part of the year. That's when you can expect those data to come up."),
    (4045.4, "Joaquin Duato", "Keeping with important data reads next year, we'll also have the data reads in our two IBD studies, ulcerative colitis and Crohn's disease, with TREMFYA. Finally, important progress in our pipeline is that we will be starting our phase III clinical program with Milvexian, our factor XI anticoagulant with our partners at Bristol Myers Squibb. I would say a very important year for us in terms of data read that will also include our phase 2 study of our oral IL-23. It's difficult for us to give you an exact timeline, but we fully expect that to happen in 2023. Many important data reads for us that will showcase the good execution that we're having in our pipeline."),
    (4097.39, "Jessica Moore", "Thank you, Louise, and thanks to everyone for your questions and your continued interest in our company. We apologize to those that we couldn't get to because of time, but don't hesitate to reach out to the investor relations team with any questions that you may have. I would now like to turn it over to Joaquin for some brief closing remarks."),
    (4116.89, "Joaquin Duato", "Thank you everyone for your questions and interest in Johnson & Johnson. While we have highlighted some of the challenges that we have in the microenvironment, we think that 2023, it's going to be another exciting year for innovation, for patients, and you can rely on us on delivering strong financial performance for both the near and the long term. Thank you very much."),
    (4145.79, "Operator", "Thank you. This concludes today's Johnson & Johnson's fourth quarter 2022 earnings conference call. You may now disconnect."),
]
paras = [{"text": t, "speakerName": s, "start": st} for st, s, t in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 35990, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)}")
