# -*- coding: utf-8 -*-
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2018-Q1.json"
ROWS = [
    (3398.93, "Joaquin Duato", "We also are expecting the data reads of our additional first-line studies, the one with Revlimid and the one in transplant eligible later this year. That body of data in first-line, it's going to be the driver of future growth of DARZALEX. What is interesting to see is that in every single study that we have done with DARZALEX, when we have had DARZALEX to different combos, DARZALEX has always, in every single one, including the ALCYONE one, has always been able to double the PFS and to triple the MRD, showing the synergistic effect that DARZALEX had in every treatment regimen."),
    (3445.87, "Joaquin Duato", "We are very positive about how DARZALEX is doing, and we believe that, as you mentioned, the next wave of growth with DARZALEX is going to come with adoption in first-line, subsequent to the approval that we'll have in this first half of the year."),
    (3462.43, "Dominic Caruso", "Jeff, I think undoubtedly our strategy in pharm has been very successful for a long period of time, which includes a good mix of internal and external development, and quite frankly, the picking the right products and collaborating with others in some very important areas, like in oncology. Good examples are IMBRUVICA and DARZALEX as two really good examples. We'll continue to do that. We just announced a collaboration with Bristol-Myers Squibb on a new anticoagulant mechanism of action of Factor XIa. That has been the hallmark of our success in pharma, and I think that'll continue. The pipeline is very strong with now eight more products we intend to file between now and 2021, each having a billion-dollar potential. Having said that, there may be times when there's an opportunity to do a great deal in pharma like we did with Actelion."),
    (3520.07, "Dominic Caruso", "That depends on the right price with the right partner at the right time. We think that generates value for our shareholders, we'll do that. I would say, we have a very good, solid pipeline already, and our collaboration strategy has proved to be remarkable, and I think that'll continue as the primary way of growing the pharma business."),
    (3542.25, "Joaquin Duato", "Yeah. If we look even forward, Jeff, the other important event with DARZALEX other than first-line approvals, it's going to be the subcu formulation. We have now four ongoing phase III studies with the subcu formulation, and we expect the filing before 2021. That would create another opportunity for DARZALEX to improve patient convenience and to continue to grow adoption."),
    (3578.51, "Joe Wolk", "Thanks for the questions, Jeff. Next question, Bob."),
    (3582.27, "Operator", "The next question comes from David Lewis with Morgan Stanley."),
    (3586.19, "Dominic Caruso", "Hello, David."),
    (3587.35, "David Lewis", "Good morning. Dominic, we're running out of superlatives to describe your tenure, I'll just say congratulations, and I hope Joe has big feet. Dominic, one for you and then just one for Joaquin here. When we think about the first quarter, Dominic, as it relates to guidance, is first quarter kind of a decent proxy for the year as it relates to growth? Basically, if pharma gets better this year, consumer gets a little better, and devices is more flattish?"),
    (3616.21, "Dominic Caruso", "Yeah. Well, I think the way to think about the first quarter, there's a few things that will not continue. For example, in the first quarter, we had some timing of tenders in Europe. You see the very strong pharma performance in Europe. That has a lot to do with the timing of tenders in Europe, and that obviously doesn't continue in every quarter. We also had this particular adjustment that we talked about that was negative in the first quarter, a catch up on rebates for one of the major payers. We do expect that we'll see an acceleration of TRACLEER and PROCRIT Generic erosion going into the balance of the year. At the same time, we expect that medical devices will continue to accelerate as well as consumer. Overall, we had some puts and takes in the first quarter."),
    (3670.23, "Dominic Caruso", "We've increased our overall guidance about a half a point from the previous expectations, and we'll update you more obviously as we see second-quarter results. Overall, I think we're in great shape, and I'm pretty confident we're going to deliver on a good solid year this year as we did last year."),
    (3689.29, "David Lewis", "Very helpful. Two thoughts for me on pharma. The first is just on REMICADE. You talked about that being one time, but is that 16% adjusted number decline, is that a good way to think about the balance of the year? For Joaquin on esketamine, obviously, a key product launch back half of this year hasn't come up much in the call. I know we'll see data here in the second quarter. Can you just talk about the size of that commercial opportunity and how you think your confidence in that commercial ramp, just given the unique dynamics of this market? Thanks so much."),
    (3720.59, "Joaquin Duato", "Thank you for the question. On REMICADE, I think that the 15%, 16% that you quoted is a good way to think about the erosion moving forward this year. Related with esketamine we are very excited about esketamine. It's been a long time that we don't have a new mechanism of action in the treatment of treatment-resistant depression. As you know, esketamine uniquely has two breakthrough assignations, one in treatment-resistant depression, the other one in suicidal ideation. We are looking forward to be able to file in the second half of this year. You're going to see more data of one of the phase III studies at the upcoming APA. What is the medical need here? You know how many people uses antidepressants, you know how many people that is using antidepressants is not getting the right response."),
    (3781.49, "Joaquin Duato", "You're talking about millions of patients in this case. It's one of the categories more used in all the pharmaceutical market. The commercial and patient opportunity is very, very significant, and I think it's one that has been underestimated generally. This is going to be uniquely, if we are able to demonstrate that in the phase III studies, which are going to be the most important thing to look after, it's going to be the first time that a new medicine is able to demonstrate efficacy on top of an active medication. That has to be never demonstrated. It would be the first time that any medicine is able to demonstrate efficacy on top of an active medication. We believe that it has very significant opportunity. It also builds on our expertise in CNS."),
    (3833.83, "Joaquin Duato", "Remember that we are the leading company in schizophrenia with our long-acting therapy franchise, which by the way, posted double-digit growth this quarter. We have a strong equity in the psychiatry community, and we have a very good understanding on how to manage site of care issues based on our experience in REMICADE and in others, helping physicians to be able to appropriately administer the medicine at the site of care. We are very confident on esketamine. We are very confident also in our capability in being able to translate good clinical data, a potential approval into patient access through our ability to manage site of care and market access for this product."),
    (3881.47, "Joe Wolk", "Thanks for the questions, David. Rob, next question, please."),
    (3885.03, "Operator", "Your next question comes from Danielle Antalffy with Leerink Partners."),
    (3889.15, "Joe Wolk", "Good morning, Danielle."),
    (3890.67, "Danielle Antalffy", "Hi, Danielle. Hi. Good morning, guys. Thanks so much for taking the question. Dominic, thank you so much for all you've done over the years. I'm very grateful for the relationship that we've developed. Joe, excited for you and to work with you going forward even more so. I just wanted to ask a question as it relates to the commentary about the incremental $30 billion now with tax reform, and how to think about the approach you guys are going to take between incremental investment in organic R&D versus inorganic capital deployment. Does that change the strategy at all or potentially make you get more aggressive on the inorganic front?"),
    (3937.99, "Dominic Caruso", "Well, Danielle, just to clarify, $30 billion invested in R&D and capital investments in the U.S., which is a 15% increase over the prior four-year period. In terms of the mix, I think we will continue to look for productivity from our incredible efforts in R&D, particularly in the pharma business, where we invest at the higher rates in the industry in R&D. I think we'll continue to maintain that. We'll continue to do, as I said earlier to an earlier question, collaborate and bring on bolt-on products in pharma as well as cross medical devices. Look, 50% of our growth over long periods of time have come from acquisition, have come from external-enabled growth, and I don't think that'll change going forward. It's just a matter of the right asset at the right price that'll create value for our shareholders."),
    (4001.84, "Dominic Caruso", "I don't see a major shift in our strategy in that regard."),
    (4006.37, "Danielle Antalffy", "Thanks so much."),
    (4007.07, "Joe Wolk", "Thank you for the question, Danielle. Next question, Rob."),
    (4010.73, "Operator", "Your next question is from Larry Biegelsen with Wells Fargo."),
    (4014.75, "Larry Biegelsen", "Good morning. Thanks for fitting me in. Dominic, congratulations on your retirement. It truly was a pleasure working with you, and Joe, congratulations on your new role."),
    (4024.14, "Dominic Caruso", "Thanks, Larry."),
    (4024.32, "Larry Biegelsen", "Two quick questions. One financial, one pharma. Dominic, you guided to $1.5 billion to $1.7 billion of other income in 2018. Does this become a headwind to EPS growth next year? Or do you expect that to remain at an elevated level via additional divestitures? I think in the past, Dominic, you've said that that line underlying other income, excluding one-time items, is about $500 million to $600 million. Is that still the case? Basically, how do you want us to think about that line going forward? I'll just quickly fit in the pharma question. It's a quick one. Joaquin, on the COMPASS trial, do you expect an FDA panel? Is it possible still to get an accelerated review? How are you thinking about that impacting XARELTO growth? Thanks for taking the questions, guys."),
    (4077.98, "Dominic Caruso", "Sure. Well, Larry, this $1.5 billion to $1.7 billion is lower than our previous guidance, as you know, and that's because of timing, primarily. Some of the activities are going to shift into 2019. That gives us \"a head start\" on that line, if you will, for 2019. We're going to continue to look at optimizing our portfolio. When we do that, we have these gains, and we typically use some of those gains to invest back in the business. You see a much higher level of R&D investment, if you compare it to any prior period when the OI&E line is lower in prior periods. It's not always just driving earnings. In fact, it's basically a portfolio decision. We're investing in new products with the gains that we get from divesting products. I think that'll be the case going forward."),
    (4134.98, "Dominic Caruso", "I think the $500 million to $600 million that I mentioned earlier is still a good underlying number for that line. As I mentioned, we're seeing improvements in our pre-tax operating margin. We expect that'll continue to grow as the consumer business ramps back up and the medical device business improves and obviously the continued strength of pharma. Even if that line is a little bit lower going forward, we have the higher pre-tax operating margin, which will drive our earnings growth. As you know, Larry, we generally look to grow our sales at a pace that's faster than the markets we compete in, but then we also look to grow our earnings at a pace that's slightly faster than the rate of growth in sales, and I think we'll continue to do that through the right mix on the P&L."),
    (4181.84, "Joaquin Duato", "Thank you for the question on XARELTO, Larry. We are very also excited about COMPASS and the COMPASS result. As you recall, we presented the COMPASS results at the ESC in August last year, and the results were impressive with 24% risk reduction in MACE. We filed in December, and we are anticipating a potential approval in the fourth quarter of this year. Regarding an advisory committee, I cannot comment on that. We don't know. What is the market opportunity and the relevance and significance of COMPASS? As we have discussed with you in the past, this is a population of about 10 million potential patients. You know that the dose would be lower, 2.5 milligram in combination with aspirin, and it's a new treatment paradigm. We are very excited about being able to bring this new therapeutic option here. It's also important from a competitive perspective."),
    (4245.42, "Joaquin Duato", "We are the only new oral anticoagulant that has this broad development program called EXPLORER that contains a reduction in MACE for CAD, PAD patients, but also other indications that I will comment, and that will enable us to do a couple of important things. First, have a new growth driver for XARELTO in addition of the existing set of indications. Second, differentiate ourselves from the competition, and in that case, gain share in the particular anticoagulant market. Third, as we will be the only one to have this indication with a differentiated dose, also have a stronger position vis-à-vis the payers. We think it's a very significant opportunity for us. As I said, this is only part of multiple phase III indication-seeking studies that we have in XARELTO."),
    (4301.8, "Joaquin Duato", "COMPASS is one, but if I can refresh your memory there, you know that we also have the MARINER, the COMMANDER studies that will read this year, respectively, in medical patients and congestive heart failure, that also represent a very significant opportunity to upgrade the standard of care of anticoagulation in these patients. Overall, the EXPLORER program that is going to start with the COMPASS study, it's going to be a growth driver for XARELTO that is going to put us in a much better position moving forward from a competitive perspective."),
    (4337.62, "Dominic Caruso", "Thanks for the questions, Larry. Rob, I think we've got time for one more."),
    (4341.88, "Operator", "That will be from the line of Bob Hopkins with Bank of America."),
    (4345.52, "Dominic Caruso", "Morning, Bob."),
    (4346.4, "Joaquin Duato", "Hey, Bob. Morning."),
    (4347.18, "Bob Hopkins", "Morning. Also let me offer my congratulations to both Dominic and Joe. Those statistics were obviously very impressive. Since the Device and Consumer Day is coming up, I thought I'd ask two quick device questions. One, on the ortho sort of pure pricing numbers that you provided in the prepared remarks. I was just curious, are those U.S. numbers? They did seem a little worse. Is there something going on with pure price that's worth calling out? That was the first question, I'll just sort of rattle off the second one. I was curious at the upcoming Analyst Day, how much detail you might be willing to provide or are going to provide on the surgical robotics JV. Will we get a lot of specifics in terms of timelines and seeing the device, or is it too early to be specific? Thank you very much."),
    (4398.35, "Joe Wolk", "Bob, with respect to the price, that was U.S. only. We provided this quarter pure price. In the past, we put it in with mix. We found out that you and your peers would simply ask for it on the follow-up call. We thought it was just a little bit more clear. In terms of overall pure price trends, we haven't seen any deviation from what's consistently been in place for the past few quarters."),
    (4421.85, "Dominic Caruso", "At the upcoming Medical Device and Consumer Day, we will have a dedicated portion of the program on surgical robotics. We'll talk about the current status of the venture that we have through Verb with Verily. We'll give you, as much as we can, a description of the current state of the robot. We'll show you some aspects of it, of course. We want to be careful as to the competitive issues that that could raise. I think we'll get a good understanding of where we are, how it works, how it's different. We'll also talk about Orthotaxy, the new knee robotic technology that we just acquired, Bob. That'll be a dedicated portion of the session to bring everyone up to date."),
    (4470.71, "Joe Wolk", "Great. Thanks, Bob, for the question and to everyone who asked a question today, and apologies to those who we could not get to due to time. Certainly don't hesitate to reach out to the investor relations team as you need to follow up. I will now turn the call back to Dominic for some closing remarks."),
    (4486.67, "Dominic Caruso", "Thanks, Joe. I want to sincerely thank all of you here in the room with me and listening on the phone for the tremendous support and partnership you've given me and Johnson & Johnson each and every quarter. It's hard to believe this is the 46th quarter that I've done this. It's been a pleasure. I also want to take one more opportunity to express my confidence in our guidance for this year, the overall success of our business. I'm very optimistic about the future of Johnson & Johnson. I look forward to seeing you all on May 16th at our Consumer and Medical Device Business Review Day. Thanks for joining us today. Have a great day."),
    (4521.31, "Operator", "Thank you. This concludes today's Johnson & Johnson first quarter 2018 earnings conference call. You may now disconnect."),
]

paras = [{"text": text, "speakerName": speaker, "start": start} for start, speaker, text in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 61782, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)} first={paras[0]['start']}")
