# -*- coding: utf-8 -*-
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2022-Q1.json"
ROWS = [
    (3332.17, "Jennifer Taubert", "Thanks for the opportunity to talk about our multiple myeloma portfolio. You know, in response to your question, you know, as we take a look at the myeloma market, despite the advances to date in therapies, there is still so much unmet need there, given the underlying heterogeneity of the disease. It's really important that there are treatment choices, and what we're really trying to do is to have a strong portfolio of highly effective treatments and actually ultimately shoot for a cure. As we take a look at the market, with DARZALEX and DARZALEX FASPRO right now, we're really seeing this as a foundational therapy for multiple myeloma."),
    (3377.75, "Jennifer Taubert", "Irrespective of, you know, others and LOE and those types of things, as you noted, it's a lot of combination therapy and things like that that does not fundamentally change the opportunity for DARZALEX and FASPRO. What I'm also really excited about is then you add in CARVYKTI that was recently approved, as we mentioned, for triple refractory multiple myeloma, and we really think that this will ultimately become a preferred treatment for patients with relapsed refractory multiple myeloma. We also mentioned Teclistamab and the filing of Teclistamab, and this really is the first ever BCMA CD3 bispecific. We think that this is, you know, gonna be a great off-the-shelf option and for patients who really are triple class exposed and who are really not eligible for CARVYKTI or don't have access."),
    (3431.91, "Ashley McEvoy", "In the future, we're not stopping there. We're also working on talquetamab, and this would be the first and potentially best in class GPRC5D bispecific that we think could be potentially sequenced and combined to help transform outcomes. As we take a look at our portfolio, we really think that these assets are additive and complementary versus something where they would be cannibalizing each other. We really think that these are the important advances that are gonna really help transform multiple myeloma in the future and going forward versus any of the older therapies."),
    (3467.87, "Joe Wolk", "Geoff, with respect to cash flow and M&A, I think I'll answer that in two parts. I think short term, we certainly have the credit rating to warrant more firepower should we need it. As you have observed, our cash flow generation over the last couple of years has ticked up to new levels north of $20 billion or around $20 billion from when we were just maybe $17 billion a few years ago. As the consumer company separates, I think that's going to be actually liberating for both sides. We still have opportunities to improve our cash flow with inventory management and receivables. But as we move to a higher growth segment, we think we'll be able to generate a similar cash flow with a higher level of sales growth, managing the P&L appropriately."),
    (3518.93, "Joe Wolk", "I've got every confidence that we'll be able to do small, medium and large scale acquisitions should the right opportunity present itself. I also think it's liberating for the consumer health segment because they'll be able to focus their cash flow generation to value creating opportunities through their particular lens being fit for purpose in a digitized environment that Thibaut spoke to. Whether it's near term or long term, I think we're in a very good position to utilize today's cash and hopefully that which should we generate tomorrow. Kevin, maybe we've got time for one more question."),
    (3555.53, "Operator", "Certainly. Our final question today is coming from Danielle Antalffy from SVB Leerink. Your line is now live."),
    (3562.21, "Danielle Antalffy", "Hey, good morning, everyone. Thanks so much for squeezing me in. This is a question for Ashley, and it's the commentary around the ASC penetration. I'm just curious, Ashley, as that site of care becomes increasingly important, where you guys think you are relative to the market from a penetration perspective and where you think you can grow, how meaningful of a growth driver will your recent success in the ASC be over the next few years? Thanks so much."),
    (3593.25, "Ashley McEvoy", "Well, thank you, Danielle. Appreciate the question. Hope you are well. We in U.S., you know, the ASCs I think are, it's still relatively low penetration, I would tell from a macro U.S., you know, less than 20%, but I think it's the fastest growing, as we know. In a COVID environment, we've seen, you know, the model evolve to create a safe, more patient-friendly experience that addresses the patient sentiment of not wanting to go into a hospital setting. Certain procedures have gone there early, you know, sooner than later. I'd say hips are migrating there and knees, less spine per se, less complicated. Obviously, trauma cases still happening in a hospital setting."),
    (3635.13, "Ashley McEvoy", "We've done a lot of work recently to modify our business model to make it a capital efficient flow, if you will, on inventory management, on the personalization of care using digital assets to kind of make your pre-op and your post-op experience less full of friction. You know, we're taking a lot of that experience in the U.S. ASCs to really what we're doing in China in the tier two and the tier three cities as well as we deliver care. I'm optimistic that this channel will continue to evolve. I do think that we've increased our competitiveness there, and we're making sure that we really have a sustainable business model going forward. Thank you."),
    (3675.41, "Jessica Moore", "Thank you, Danielle, and thanks to everyone for your questions and your continued interest in our company. We apologize to those who we couldn't get to because of time, but don't hesitate to reach out to the investor relations team as needed. I will now turn the call back to Joe for some brief closing remarks."),
    (3692.59, "Joe Wolk", "Great. Thanks, Jess. As Jess alluded to, we certainly do appreciate your questions and the chance to interact with you. I'd like to remind everybody as we close that we do have the opportunity to engage with shareholders at next week's annual meeting on April 28th. Also, be on the lookout for an update on our commitments to ESG. On June 8th, we will be issuing our Health for Humanity report, which is an in-depth review on the progress we are making on our 2025 goals. Thank you for your time and your interest in Johnson & Johnson. Have a great day."),
    (3725.99, "Operator", "Thank you. This concludes today's Johnson & Johnson's first quarter 2022 earnings conference call. You may now disconnect."),
]
paras = [{"text": text, "speakerName": speaker, "start": start} for start, speaker, text in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 19015, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)} first={paras[0]['start']}")
