# -*- coding: utf-8 -*-
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2022-Q2.json"
ROWS = [
    (3535.11, "Joaquin Duato", "It's a very serious situation that will affect innovation, will affect our ability to invest in R&D and to develop new medicines. Now, we are also engaging with different stakeholders in trying to educate them about the impact of this type of legislation and innovation. At the same time, we also want to sit at the table and participate in discussions to address what we believe is the major issue, which is patient affordability and patient access, specifically in Part D. We think that that's something that the industry has to address with the relevant stakeholders, and we are very willing to sit at the table and shoulder the consequences of being able to address the patient affordability issue."),
    (3581.03, "Louise Chen", "Now, I always need to remind you that in a price-constrained environment, Johnson & Johnson performs relatively better than most of our peers and competitors based on a number of factors. First, our diversification. Second, we have about half of our sales that come outside of the U.S. Third, specifically in the pharmaceutical business, we have been able to deliver above-market growth in the face of mid-single-digit net price decreases. We know how to grow in a difficult pricing environment. As a matter of fact, you know, all of our growth comes from volume. If you're thinking about, you know, where to be in these circumstances, Johnson & Johnson, really, it's a good place based on its diversification and our ability to drive growth through volume."),
    (3631.25, "Jessica Moore", "Wonderful. Thank you, David, and thanks to everyone for your questions and your continued interest in our company. We apologize to those that we couldn't get to because of time, but don't hesitate to reach out to the investor relations team with any remaining questions that you may have. I will now turn the call back to Joaquin for some brief closing remarks."),
    (3650.87, "Joaquin Duato", "Thank you, everybody, for participating in the call. Again, very pleased with the solid results achieved by our teams year- to- date. It shows the quality and the market leadership of our franchises and the great execution of our company in the middle of these challenges. We are also making good progress in the three strategic priorities that I outlined at the outset of this call regarding the consumer separation and the creation of the new Johnson & Johnson, our ability to continue to grow in our pharmaceutical business through the STELARA patent expiration, and our continued recovery and competitive growth at MedTech. As we conclude today, also a quick reminder on our recent ESG investor update, which highlighted progress against our 2025 Health for Humanity goals."),
    (3701.31, "Joaquin Duato", "I encourage all of you to listen to the webcast replay on our website if you didn't have a chance to do it already. We look forward to connecting with all of you again and keeping you updated on our continued progress on future earnings calls. Thank you very much."),
    (3719.71, "Operator", "Thank you. That does conclude our webcast and teleconference today. You may disconnect your line at this time and have a wonderful day. We thank you for your participation today."),
]
paras = [{"text": text, "speakerName": speaker, "start": start} for start, speaker, text in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 26129, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)} first={paras[0]['start']}")
