# -*- coding: utf-8 -*-
import json
from pathlib import Path
REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2022-Q3.json"
ROWS = [
    (3382.36, "Jennifer Taubert", "Maybe if I start off on CARTITUDE-4 and then I'll come back on the launch. We do anticipate CARTITUDE-4, you know, hopefully reporting by year-end. It's an event-driven trial, so we have to wait until we have all of the events. But that's currently what we're planning for now. So that everyone knows, CARTITUDE-4 is our study that takes a look at CARVYKTI, in 1-3 prior lines of therapy. We're really interested and looking forward to seeing those results. If we take a look at the early launch for CARVYKTI, we've always talked about this being a really, you know, planned and thoughtful approach to scaling it. We're in the process right now."),
    (3423.9, "Jennifer Taubert", "We've really been working closely with the centers where we had done the clinical trials to work through the initial phases. I know everyone knows about the worldwide Lentivirus shortage. We've made really good progress on that and have good line of sight to that not being a rate-limiting factor in the future. We're also working towards really being able to scale this at a broad level to be able to accommodate what we're seeing as both great demand for the product right now, but also what we anticipate with CARTITUDE-4, as well as hopefully with CARTITUDE-5, which would be in frontline therapy. We reconfirm this as really a big asset with a lot of growth potential and 1 of our potentially $5 billion-plus brands."),
    (3473.56, "Jessica Moore", "Thank you, Jeff. Kevin, we have time for 1 last question."),
    (3477.66, "Operator 1", "Thank you. Our final question today is coming from Terence Flynn from Morgan Stanley. Your line is now live."),
    (3483.68, "Terence Flynn", "Hi. Thanks so much. Maybe a couple pharma ones for me as well. I was just wondering, as you think about the combined franchise for Stelara and Tremfya next year, can that grow versus this year? Then based on ClinicalTrials.gov, it looks like the Nipocalimab phase 2 RA trial recently completed. Just wondering if you can provide any color if you're going to advance that into a phase 3 trial for RA. Thank you."),
    (3510.02, "Jennifer Taubert", "Thanks, Terry. First question. Stelara and Tremfya. We don't provide sort of, guidance by product or, you know, or combinations of that. What I can say is that we do anticipate continued robust growth for Tremfya next year. As I indicated, Tremfya in psoriasis and psoriatic arthritis is really showing very strong market share gains and penetration in that market. Stelara really competes, and its strong growth has been in Crohn's disease and ulcerative colitis. When you take a look at those 2 markets, we do anticipate both of those continuing to show really good growth, at least through the first 3 quarters of next year with Stelara then, you know, post-September being impacted by biosimilars. Then on Nipocalimab."),
    (3569.9, "Jennifer Taubert", "I don't have really anything to share there yet. For Nipocalimab, you know, consistent with all of our, you know, processes, when we finish our studies, we go ahead and submit them to major medical meetings and get them published. I remain really confident in Nipocalimab as an asset, and we've really taken a look at building that out across 10 or 11 different indications, including the potential for RA, which we think could be a big one. Definitely more to come on that, as we can share it."),
    (3605.18, "Jessica Moore", "Thank you, Terence, and thanks to everyone for your questions and your continued interest in our company. We apologize to those that we couldn't get to because of time, but don't hesitate to reach out to the investor relations team with any remaining questions you may have. I would now like to hand it over to Joe for some closing remarks."),
    (3622.88, "Joseph J. Wolk", "Great. Thanks, Jess. Thank you, Thibaut, Ashley, Jennifer, and Jessicah for participating in today's call. As Jessicah said, thanks to all of you for your time today. Hopefully, you saw with our third quarter performance the strength of Johnson & Johnson across all of our segments and our collective ability to manage macroeconomic headwinds as well as the unfavorable impact from a stronger U.S. dollar. We certainly take seriously our responsibility to be a reliable, strong investment, in many ways for shareholders, even though uncertainty may be high. Have a great day, and we look forward to our next conversation."),
    (3659.56, "Operator 1", "Thank you. This concludes today's Johnson & Johnson's third quarter 2022 earnings conference call. You may now disconnect."),
]
paras = [{"text": t, "speakerName": s, "start": st} for st, s, t in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 38648, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)}")
