# -*- coding: utf-8 -*-
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2021-Q1.json"
ROWS = [
    (3564.57, "Danielle Antalffy", "One is really on the devices. I think, Joe, you alluded to this when you were talking about growth comparisons to 2019. There was still a COVID impact in Q1, and I guess I'm just trying to get a sense of how Q1 sort of shaped up as you worked through the month. Did you see a strong recovery in March in the device side of things? Do you feel like, and this might be an ambiguous and kind of difficult question to truly answer, but I guess, do you feel like the worst is behind us, even regardless of how vaccinations continue to roll out and what variants might do? Then I have one vaccine follow-up."),
    (3627.25, "Alex Gorsky", "Hey, Danielle, this is Alex. Thanks a lot for your question. We do there expect to see improving trends in the medical device arena. If we take a look at the first quarter, there was some irregularity just based upon what we were seeing with the virus and on a global basis in January versus February, March. Overall, it's clear to us that we're seeing improving trends. As Joe alluded to in his earlier comments, we would expect that just given. [inaudible]."),
    (3674.7, "Danielle Antalffy", "What are the alternatives for the volumes that were supposed to be manufactured out of Emergent, if in a worst-case scenario, Emergent is prevented from being able to produce for the next few months?"),
    (3686.36, "Joaquin Duato", "Thank you, Danielle. Look, as Paul said, our goal remains ensuring that all drug substance for our COVID-19 vaccine meets our high quality standards and at the same time that we secure emergency use authorization for the drug substance manufacturer at the Emergent Bayview facility. At this time, as we continue in discussions with the FDA, it is premature to speculate on any potential impact that this may have on our timing of our vaccine deliveries. We will expect to work with the FDA to close this inspection this week, and then we will work with the FDA and Emergent to address those inspections findings. At this time, it would be premature to speculate on any potential impact that this could have on our delivery timing."),
    (3743.6, "Chris DelOrefice", "Great. Thanks. Just real quick to build on Alex's comment, maybe just to give you a little bit of color. We're obviously looking at procedures closely, surgical procedures, imaging as well. Diagnostics is actually outpacing surgical procedures. It accelerated through the quarter. It's almost in line with where we were pre-pandemic. That's a positive sign, although the situation, of course, remains fluid. Many important procedures such as colorectal, again, sequentially improved through the quarter, and actually grew year over year. Again, we're seeing positive signs across, and I think you saw that in our results in pockets of our business, advanced surgery, for example, growing over 14%. We're continuing to look at everything. The situation remains fluid, but there's definitely positive signs in the trends that we're seeing. Thanks, Danielle. Rob, next question, please."),
    (3796.56, "Operator", "Next question comes from Matt Miksic with Credit Suisse. Please proceed with your question."),
    (3802.2, "Matt Miksic", "Thanks so much. I've got one sort of utilization-related question on procedure trends and then I have a follow-up for Alex, if I could, on digital strategy. First, devices up 8.8%, stronger than the street was expecting. The mix also a bit stronger than expected on advanced surgery, and maybe a little bit slower as has come up on Q&A here than expected. Knees, which you mentioned, Alex, is a couple of times as being more deferrable. The question is, should we read through this as a bit of a shift to higher acuity procedures within your portfolio? Maybe how should we see the recent rise in hospitalizations potentially affecting the trajectory of recovery over these procedures over the next months and quarters? As I mentioned, I have one follow-up on digital."),
    (3856.16, "Alex Gorsky", "Sure, Matt. Thanks a lot for the question. Look, Matt, overall, I wouldn't read too much into just these recent results regarding a significant shift overall in our portfolio. We remain very committed and optimistic about the underlying unmet need and demand across our surgical portfolio, our orthopedics portfolio, and our vision care portfolio. As we alluded to earlier, there are some procedures that in terms of your ability to defer, and how electable they truly are, that may have a near-term impact on timing. Look, overall, if we look at our underlying trends, not only versus 2020, but as was noted earlier, also versus 2019, we're seeing growth rates consistent overall with what we see for this market."),
    (3911.2, "Alex Gorsky", "We see it grow at about the 5% range over the long term, and we've been very explicit in our goal to grow at or faster than the markets where we compete. That's number one. Number two, we're actually very excited about some of the opportunities that we have for launches. I think in total, we have more than 21 major launches lined up in our medical device business for this year. I mentioned specifically in the knee area, VELYS, as well as our ATTUNE cementless fixed bearing, which we think will offer us a real competitive opportunity to generate additional growth in that area. The QDOT MICRO is another great add-on in our EP business that is already growing in excess of 20%. If you look across our ENDO MACK, our energy business here too, we've got really nice add-on innovations as well as throughout our vision care portfolio."),
    (3966.08, "Alex Gorsky", "Of course, longer term, the significant opportunity that we see in digital surgery. That team has continued to make very solid progress. We're excited about the long-term prospects there as well. No, overall, we see a lot of opportunity across our medical device portfolio."),
    (3986.48, "Matt Miksic", "That's great. Maybe just to segue on your second point there about digital. You mentioned robotic knee systems on track, MONARCH obviously leading the market in robotic-assisted lung, and OTTAVA is sort of tracking through clinicals and validation. The question is what else? You've built out this portfolio of artificial intelligence robotic surgery applications and technology. What are the white spaces? Where else do you see investments within digital?"),
    (4023.39, "Alex Gorsky", "Well, look, we believe we're in the very early innings of digital, Matt. First of all, if we just look at the overall penetration rate of digital surgery, it's about 10% in the U.S. It's just a couple % on a global basis. We think if you consider the overall trends of how technology can be utilized in some of these procedures, if you take a look at our global footprint, we think we will be well-positioned there in the long term. As you mentioned, our team has continued to make good progress. We said from the very beginning, look, we're building this for the decades. We're not just building this for the next quarter. We're optimistic about the progress that team has been making to ensure that we've got a platform that, one, can truly make a difference for patients and surgery."),
    (4075.15, "Alex Gorsky", "That two, that's differentiated. Three, that also allows us to integrate not only the robotics aspect, but also the digital component that we think long term can truly help show very significant differences in surgical outcomes. Also, just to give you one example of an application. We've mentioned this before, but in Johnson & Johnson right now, and I think this exemplifies the unique nature of our diverse portfolio. Several years ago, we embarked on something that we call the Lung Cancer Initiative. As we know, unfortunately, lung cancer continues to kill more people than just about any other type of cancer. We know that all too often, patients are diagnosed far too late in the process."),
    (4126.53, "Alex Gorsky", "We're quite excited about an early application with MONARCH, where we're not only able to go out and potentially do a diagnostic procedure through bronchoscopy to identify, for example, lung nodules, but we're working right now on how can we deliver oncolytic agents, viruses, and other immune type agents locally. How could we really think about the treatment paradigm being shifted in the way that we fundamentally think about lung cancer by combining pharma, medical device, some of these technologies in very new, unique, and innovative ways. Still much more work to be done, but we're very excited about some of the early prospects that we've seen thus far. Again, I think it exemplifies kind of our unique position to bring these different clinical development, discovery, as well as regulatory capabilities and eventually commercial together."),
    (4188.27, "Chris DelOrefice", "Great. Thanks, Matt. Appreciate the question. Rob, we'll take our last question now."),
    (4192.71, "Operator", "Yes, the question comes from the line of Terence Flynn of Goldman Sachs."),
    (4197.31, "Terence Flynn", "Hi, good morning. Thanks for taking the questions. Recently, there's been some new post-marketing data reported for Xeljanz, and the FDA pushed out the PDUFA dates of several JAK inhibitors. You guys are developing a pan-JAK inhibitor for IBD. I would just love your latest perspective on the risk-benefit profile of the category here and next steps in your development program. I just wanted to confirm that you're on track to supply 1 billion doses of your COVID-19 vaccine this year. Thank you."),
    (4226.61, "Joaquin Duato", "Thank you for the question on immunology. Look, I'm not going to comment on the safety of the oral JAK inhibitors. What I can tell you is that we have a very strong and robust pipeline in immunology driven by our three existing assets, Simponi, Stelara, and Tremfya. Stelara and Tremfya had very strong quarters with close to 40% growth in Tremfya and 15% in Stelara. In Stelara, we continue to grow share in GI, both in Crohn's disease and ulcerative colitis. Tremfya is the first and only IL-23 that does have both indications, PSA and PSO, and it's continued to gain share in both areas. Moving forward, we are excited about our possibilities in immunology with our oral agents. As you mentioned, one, we have two in phase II. One of them is a pan-JAK oral that we think could be important."),
    (4287.75, "Joaquin Duato", "We'll have to see the data. Broadly in immunology, we also are excited about the possibilities of nipocalimab, which is our FcRn antibody in pathways that are autoantibody mediated with very rare diseases that could create a pipeline in a product. For us, immunology remains a core area of growth and focus, and we believe we are in a very strong position to continue to drive growth in the coming years, but even beyond 2025 too."),
    (4321.77, "Joe Wolk", "Yeah, maybe Terence, just to pile on to what Joaquin outlined there with the strength of our pipeline. In pharmaceutical specifically, we're looking at 10 new filings. That could be new products or indications in 2021, 13 in 2022, and 26 in 2023. You can see that R&D investment incrementally paying off. With respect to your second question regarding supply, I want to be respectful of the process by which the regulators are going through. We are remediating what we need to remediate. We think that will lend itself to a positive outcome and should put us in a position to all of our contractual commitments as they stand today. Let's be respectful of the process and let that play out. We're going to do all we can and provide that effort."),
    (4371.07, "Joe Wolk", "As you know, and as you've heard in the press, we do have some of our best personnel on site at Emergent, so they're benefiting from our expertise. We should know more in the next couple of days."),
    (4383.15, "Chris DelOrefice", "Great. Thank you, Terence, thanks to everyone for your questions and continued interest in our company. Apologies to those we couldn't get to because of time, don't hesitate to reach out to the investor relations team as needed. I'll now turn the call back to Alex just for some brief closing remarks."),
    (4398.05, "Alex Gorsky", "Well, let me end where I began, first of all, by thanking all of you for your insightful questions and your ongoing support. Two, and also by thanking all of our associates at Johnson & Johnson, almost 140,000 who have been working 24/7, particularly over the last 15 months during this pandemic period. We appreciate your ongoing interest and your support and look forward to updating you at our next quarterly call. Thank you very much and have a great day."),
    (4425.93, "Operator", "Thank you. This concludes today's Johnson & Johnson's first quarter 2021 earnings conference call. You may now disconnect."),
]
paras = [{"text": text, "speakerName": speaker, "start": start} for start, speaker, text in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 3933, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)} first={paras[0]['start']}")
