# -*- coding: utf-8 -*-
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2018-Q3.json"
ROWS = [
    (3389.38, "Joseph Wolk", "Sure. Thanks for the question, Danielle Antalffy. With respect to transformative deals or tuck-in deals, again, we look at all scale of deals. Last year alone in Medical Devices, we invested slightly over $1 billion with 30 tuck-in deals, and you're seeing some of that improve the performance within the Medical Devices segment right now. Again, it's going to come back to those core principles of making sure it's a strategic fit and then creating value for shareholders."),
    (3423.7, "Ashley McEvoy", "I would just complement that, Danielle Antalffy, with just saying, again, historically, 50% of innovation has come from inorganic versus organic, and that blend will continue. As Joseph Wolk mentioned, even in 2018, we've already done 26 deals. Some of those acquisitions, some of those equity, some of those co-promotes. It really has to do with the strategic fit and the value creation in each of the platforms that we compete in."),
    (3450.62, "Danielle Antalffy", "Thank you very much."),
    (3454.68, "Operator", "Next question comes from Jayson Bedford with Raymond James."),
    (3460.08, "Jayson Bedford", "Good morning. Thanks for taking the questions. Just a couple quickies. First on devices, maybe for Ashley. The 23% growth in Biosense Webster is a notable step up. You mentioned contribution from new products, you also talked about strong procedure growth. I'm just wondering, have you seen any pickup in market growth from the CABANA results last spring?"),
    (3486.7, "Ashley McEvoy", "Thank you, Jayson. Yeah, we did enjoy 23% growth in quarter three. I think it's been a very strong combination of market procedures continuing to increase, as well as a very strong focus on commercial execution and market creation on ablation, as well as very balanced geographic growth. We enjoyed in our Biosense Webster business growth of 34% in Asia and 11% in EMEA, as well as 20% in North America. Again, combination of core performance as well as some of the new products taking effect."),
    (3528.62, "Jayson Bedford", "Okay. Thank you."),
    (3530.26, "Joseph Wolk", "To the CABANA data, I would say that it maybe had a slight impact in terms of overall procedural market growth, nothing that the team called out as a significant driver."),
    (3542.38, "Jayson Bedford", "Okay. There's clearly some share capture here in your view."),
    (3557.0, "Joseph Wolk", "Next question, please."),
    (3559.66, "Operator", "Sorry. The next question is from Amit Hazan with Citi."),
    (3564.62, "Amit Hazan", "Oh, thanks. Hey, good morning, guys. Just maybe start with the utilization stats that you guys give. The U.S. surgical procedures are now up for a second straight quarter in a row after I think seven straight down quarters. I'm just wondering if you guys could take a stab at trying to explain what might be happening with underlying surgical procedures in the U.S."),
    (3589.16, "Joseph Wolk", "Thanks, Amit, for the question. Go ahead, Ashley."),
    (3591.34, "Ashley McEvoy", "Go ahead, Joe."),
    (3594.04, "Joseph Wolk", "Amit, I think when we look at a strong economy across the globe, where is really where our strength has been. If you look, we're actually growing outside the U.S. stronger 2x what we've grown here in the U.S. A strong economy does tend to lend itself to better coverage and better healthcare. That is helping underpin some of the procedural growth that we're seeing."),
    (3619.3, "Amit Hazan", "Okay. Then specifically though with regard to your surgery business, the U.S. advanced piece in the U.S., it was obviously a good number this quarter, you're actually still trending at about 2% growth for the year versus about 6% for the past few years. Maybe just some color for you guys on why you're having slower growth in advance this year, and it's kind of a similar trend in U.S. general as well."),
    (3645.04, "Ashley McEvoy", "I think, Amit, this is Ashley speaking. A couple of things. One, in our Ethicon surgical business, clearly we enjoy many market-leading positions, and I'll come back to the mix. What I'm pleased to see is that our Endocutters business is up 10% in quarter three, our biosurgery up 9%."),
    (3666.58, "Ashley McEvoy", "Consistent growth in our wound closure where we enjoy market leading, really driven by some innovation on barbed sutures and a lot of evidence generation strategy related to the antimicrobial effect for infection reduction. We are seeing challenges, clearly, in reprocessing and robotics in some of our energy and endomechanical business. Out OUS, our energy business is performing quite well. We are experiencing some challenges in the U.S. related to robotics and some reprocessing. I do expect that when the advancement of our robotic offering and digital surgery in the forthcoming years, that will help ameliorate that. We've also dialed up the innovation agenda in our endomechanical and energy business to really stronger compete in the handheld market."),
    (3720.14, "Chris DelOrefice", "All right. Thanks very much, Deb."),
    (3723.7, "Operator", "Your next question is from the line of Vamil Divan with Credit Suisse."),
    (3729.18, "Vamil Divan", "Hi, great. Thanks for taking my question. Just a couple, maybe just one to follow up on some of the comments around drug pricing. We've seen a lot from the administration. Yesterday, obviously, the proposal came out around needing to include pricing in some of the TV ads, I'm just curious if you can maybe provide your perspective on this issue. Just, do you think this is something that'll be useful or not useful maybe more broadly, any other sort of broader changes that you think might be implemented by the administration as things have sort of played out here over the last several months? Second is just on DARZALEX. Appreciate the comments you made about the quarter. I'm just curious about the MAIA study, I think that was previously listed as a potential clinical presentation this year."),
    (3774.43, "Vamil Divan", "It's not on the key events slide now. I'm assuming you're still going to get that internally just a couple of people asking is if you can clarify exactly when you expect that data, should we expect some sort of top-line press release when you receive it, maybe, again, generally how important that data is to the longer-term outlook for that product. Thanks."),
    (3794.46, "Jennifer Taubert", "Sure. As it relates yesterday to the administration's proposal, as well as, hopefully you saw as well that PhRMA put forward some new principles that the PhRMA members will be adhering to. We really believe that patients should have access to the information that is helpful that they can use to make the best decisions regarding their health. This does include greater transparency around healthcare costs. We've been a leader in transparency to date. That's why we provide information about how we price our medicines, how we invest our resources in our annual U.S. transparency report. We are absolutely working in partnership with PhRMA around PhRMA's announcement yesterday what we can do on DTC pricing."),
    (3843.3, "Jennifer Taubert", "This has been done in line with what we learned from customers and patients what they think is actually going to be helpful, which is not only information on list pricing, but also putting that information into the right context. What that actually means for them, since list price is really just a starting point. For patients, what is their likely out-of-pocket cost going to be? What type of financial assistance is available in addition to information like the list price. We're going to respond to the agency's proposal. There's 60 days. We're going to go ahead respond to that provide our input. In the meantime, go ahead implement what we're executing what we're doing in line with PhRMA on that."),
    (3897.2, "Jennifer Taubert", "I think anything that is helpful and useful to patients and helps put all the information in context is going to be really good for them. I think we just need to be careful of things such as list price alone, is not the full extent of the information, and we would worry about patients not going to their doctor to seek care, not going in for their appropriate treatment. We believe we're doing the right thing with the PhRMA proposal, and we'll just have to wait and see what happens with Alex Azar's proposal that he announced yesterday."),
    (3929.66, "Chris DelOrefice", "Yes, regarding DARZALEX, it's a 2019 filing. It's an event-driven, that's all we're sharing at this point in time."),
    (3938.36, "Jennifer Taubert", "We're very optimistic about that data, and we think it'll be an important further catalyst for DARZALEX, is that data, it will be the regimen that is most commonly used in the United States. We already have that frontline data in use with VELCADE, ex-U.S., as well as approved in the U.S. We think the data, including REVLIMID, is going to be really important going forward for the U.S. market."),
    (3962.76, "Vamil Divan", "Okay, thanks so much."),
    (3966.38, "Operator", "Your next question comes from Bob Hopkins with Bank of America."),
    (3971.28, "Bob Hopkins", "Oh, thank you very much. Good morning. Joe, if okay, I wanted to ask a quick question on emerging markets. Obviously, emerging markets have been in the press quite a bit lately, both in terms of the volatility of currency and emerging market economies. I'm just curious, can you give us a sense in your third calendar quarter, kind of what happened to your businesses in emerging markets? Maybe some flavor by division, if okay, just in terms of did anything really change in terms of underlying demand or the growth rate that you achieved in emerging markets in your three big divisions? Thank you."),
    (4003.08, "Joseph Wolk", "Yeah, thanks for the question, Bob. In our emerging markets, we saw very healthy growth. In total is about, on an operational basis, almost 13%, and it was pretty uniform across the board. I would say BRIC specifically was very strong with 15% or better growth in Brazil, Russia, and China. Maybe I can turn it over to Jorge because we did see some particular strength out of our consumer business and maybe just talk about the consumer results"),
    (4032.58, "Joseph Wolk", "At large in the third quarter, obviously, that was a significant step change for us, performing what we believe is going to be twice the market. Jorge, maybe if you can share a few of those thoughts."),
    (4042.8, "Jorge Mesquita", "Sure. Thanks, Joe. Yes, we feel very good about our results in the third quarter, growing overall north of 6% organically. As Joe mentioned, the emerging markets contributed to this growth, growing above 10% across the key geographies. Particularly, we saw a very strong performance in the BRIC markets, we continue to expect that over time, the emerging world will continue to grow at twice the rate of our business at a global level. Underpinning our performance was a significant improvement in our Johnson's Baby business. We are very pleased with the early results coming out of our restage here in the U.S. As Joe mentioned, we are now going to roll that out across the world, starting with India and China, we expect to complete the global rollout across the emerging world into 2019."),
    (4099.52, "Jorge Mesquita", "Despite the occasional volatility in some particular markets, I think overall, we are bullish on the outlook for the emerging world as we go forward."),
    (4110.68, "Joseph Wolk", "Great. Thanks, Jorge."),
    (4113.66, "Bob Hopkins", "Yes, that is super helpful. Maybe just, Joe, one quick follow-up on that. It sounds like underlying demand is very strong across the board, especially as you mentioned, consumer. Given the volatility in emerging market currencies, maybe just qualitatively or quantitatively, as you look forward, is that a meaningful headwind to reported EPS as we look forward given the volatility? Is that something that is, in your mind, very manageable relative to all the different moving pieces that are involved with the J&J income statement?"),
    (4141.2, "Joseph Wolk", "Yeah, Bob, it's a good question. I would think it should be a manageable headwind, and obviously, it's going to depend on how much currencies fluctuate. We're not overly tied to currencies in emerging markets, it should be manageable."),
    (4156.96, "Bob Hopkins", "Terrific. Thanks. Taking the questions."),
    (4158.44, "Joseph Wolk", "I just want to take a moment here, too, and follow up maybe on Jennifer's comments with respect to Alex Azar's proposal, and just be very clear that we support the administration's spirit of transparency and getting more information out there. I think the position of PhRMA right now is we want to make sure that we provide that information in a way that's meaningful and provides clarity to patients. Having list price on DTC ads could be somewhat confusing and actually act as a deterrent to good, responsible healthcare. We just want to make sure that that doesn't play out that way. Certainly, looking to digest the proposal and put it into practice the best way possible that's meaningful for patients and the healthcare system."),
    (4204.7, "Operator", "Your next question comes from Geoff Meacham with Barclays."),
    (4209.64, "Geoff Meacham", "Morning, guys. Thanks for the question. Just had a few for Jennifer and maybe Joe, too. To revisit the 2019 question, I know you guys haven't given a formal view, given the headwinds on pharma organic growth from ZYTIGA and the other LOEs, if you're not above market growth, does that change strategic priorities, either your attitude towards deals or investments across different therapeutic categories?"),
    (4232.5, "Joseph Wolk", "Yeah. Geoff, maybe the first thing is to clarify the question in that we currently believe we are the holder of a strong patent, and we plan to defend those rights. We're looking forward to the judge's decision later this month. As Jennifer indicated, our growth, even without ZYTIGA, was very strong. There are some potentially generic headwinds on the horizon. Should that, for some reason, put us below market, which is not something that other companies face given the breadth of our portfolio. We've got 12 brands in pharmaceuticals that deliver better than $1 billion in revenue. We can absorb that. We're not in a situation where we're going to take a year or two off from growth, and anything that's at market is probably only temporary because we've got good confidence in our pipeline going forward."),
    (4289.69, "Geoff Meacham", "Okay. That's helpful, Joe. A few product-specific questions for pharma. For DARZALEX, how has the duration of therapy been tracking, and how do you guys see the refractory myeloma space evolving when you look at the cell therapies for BCMA? On XARELTO, just want to get a sense for the feedback from the field following MARINER and COMMANDER since the ESC, and just trying to put these data in context of the overall brand. Thanks."),
    (4318.24, "Jennifer Taubert", "Sure. I can start off on the XARELTO piece. We just got approval last week for CAD and PAD, and the team is actually out launching it as we speak. Product is in the market, and the teams are out in the market launching and bringing XARELTO in the 2.5 milligram dose to patients. We're really excited about the opportunity to expand XARELTO as the first Factor Xa inhibitor in the CAD/PAD space, which expands the opportunity by, I think, 13 million additional patients in the U.S. alone. The data is quite striking in that indication, 24% reduction in CV death, stroke, and heart attack. We're really very optimistic about this launch for XARELTO."),
    (4369.5, "Jennifer Taubert", "As it relates to MARINER and the data that we have across the medically ill space, we are working with the agency on that and do believe that there's a good path forward in that space for XARELTO. Probably can't say any more than that on that right now, but we will be continuing to pursue that with the FDA going forward. We believe there's good reasons for future growth in XARELTO, as well as continued growth in share gains in both the AFib and DVT prevention and treatment space. The other question was on-"),
    (4405.54, "Geoff Meacham", "Around-"),
    (4405.82, "Jennifer Taubert", "Sort of CAR T and DARZALEX"),
    (4407.38, "Geoff Meacham", "DARZALEX and CAR T, how that might play together?"),
    (4408.74, "Jennifer Taubert", "Yeah. We actually think that they're complementary in the multiple myeloma space, and so we're very excited about CAR T. We've dosed our first patient already, which is a very, very fast timeline versus when we did that deal with Legend. I think if you take a look at the unmet medical need in multiple myeloma, it still remains a significant need. I think having both DARZALEX as well as what we've got with the BCMA CAR T together will be a nice portfolio for patients, which will allow us to continue to grow."),
    (4447.06, "Geoff Meacham", "Okay, great. Thank you."),
    (4452.54, "Chris DelOrefice", "Great. That concludes today's Q&A portion. Thanks to everyone who asked a question today, and apologies to those who we could not get to due to time. Please don't hesitate to reach out to the investor relations team as is needed with any follow-ups. I'll now turn the call back to Joe for some closing remarks."),
    (4469.7, "Joseph Wolk", "Great. Thanks, Chris. Thank you, Ashley, Jorge, Jennifer, for sharing your insights on our business and delivering with your teams very strong results for the third quarter. I hope it is clear to you and the investment community that our business is very strong, and we look forward to living into the new guidance that we have articulated earlier today for 2018. Thanks for your interest in Johnson & Johnson, and we look forward to speaking with you soon. Have a good day."),
    (4496.68, "Operator", "Thank you. This concludes today's Johnson & Johnson's third quarter 2018 earnings conference call. You may now disconnect."),
]

paras = [{"text": text, "speakerName": speaker, "start": start} for start, speaker, text in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 61779, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)} first={paras[0]['start']}")
