# -*- coding: utf-8 -*-
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2019-Q2.json"
ROWS = [
    (3205.53, "Paul Stoffels", "That's where we are aiming for finally. If you look into Orthotaxy, we continue to receive great feedback about that platform. It's especially about its smaller footprint, the fact that it is an imageless system, and the surgeon's freedom to move within the cutting plane defined by the robot. That results in an overall ease to use, which is greatly appreciated by the surgeons. Finishing up with Verb, as you expressed the confidence in the platform and the value proposition, we recently successfully completed a series of end-to-end procedures engaging a group of global KOLs across a subset of target specialties, including general and with hernial, colorectal, and bariatrics, in urologic, in gynecologic, and thoracic surgery."),
    (3252.59, "Paul Stoffels", "We continue to believe our system will address the current limitations of robotic surgery, such as access and reach, the footprint and cost, and the workflow and advanced instrumentations to such a much better outcome. I was personally able to operate one of the instruments in the lab, and it's really a very impressive new robotic surgical tool. Also overall, the surgeons, their feedback continues to be very positive on the product. Overall, a very good start. Hard work for us and lots of development to be done, but on a very good path."),
    (3289.99, "Chris DelOrefice", "Great. Thank you, Paul. Thanks, Kristen, for the question. Operator, next question, please."),
    (3296.03, "Operator", "Yes. The next question is from the line of Terence Flynn with Goldman Sachs."),
    (3301.13, "Terence Flynn", "Hi. Thanks for taking the questions. Was wondering on the R&D spend you mentioned on the pharma side, it sounds like that ramp is mainly external opportunities, but was wondering if there's any internal programs that you're going to be ramping spend on, if you can be any more specific there. Then on DARZALEX, any insight you can provide on average treatment duration now and how you see this evolving over time, and then any initial thoughts on how you're thinking about pricing the subq formulation. Thank you."),
    (3330.81, "Joaquin Duato", "Let me start with DARZALEX and telling you that we are very pleased with the progression of DARZALEX. We had a very strong growth in the quarter with 57%, 41% when you neutralize for the one-time price effect. We are pleased with the progression of DARZALEX and the strong growth that we are having across all lines of therapy. Particularly, recently we had two important events. One is the approval of the frontline indication in transplant-ineligible patients in the combination with REVLIMID, which was much anticipated, and that will give us, together with the filing of the also frontline indication in transplant-eligible, will give us three indications in frontline. To your question on the duration, as we move into earlier lines, the duration of the treatment increases."),
    (3388.59, "Joaquin Duato", "When it comes to the subq that we filed earlier this week, we think this is a very important opportunity for DARZALEX overall. Keep in mind that we're going to be able to reduce the infusion time from eight hours that we have today to five minutes. That's going to give significant advantages in terms of adoption of DARZALEX, in particular in earlier lines, and particularly when you think that 50% of the use of DARZALEX today in the U.S. is in oncology clinics in outpatient patients."),
    (3423.79, "Joaquin Duato", "We think that this combination is going to make DARZALEX easier to use for physicians and more convenient to patients that if you add to that the number of studies in which we are showing very strong results in frontline will portend for a very positive continual adoption of DARZALEX that we see one of the major drivers of the growth of the pharmaceutical group."),
    (3453.11, "Paul Stoffels", "With regard to the spending, internal or external, once we bring in an asset internally, we consider it all as internal spending. The external spending we do is on milestones and upfronts, and that has been a very effective way to create value for us. We do less acquisitions, we invest a lot in external innovation in early stages through collaborations, through our JLABS, and also through our venture capital, and then through acquisitions. Once we acquire products, it becomes part of a portfolio, and we continue to drive the success of that. We have a significant number of internal-derived opportunities, let's say at the moment in the range of 50/50, 60/40 of products coming from our own portfolio as products which we brought in. We invest also something like 50/50 in new products, but also, as Joaquin was saying, in line extensions."),
    (3513.47, "Paul Stoffels", "Line extensions are great opportunities to have de-risked products and get additional indications and additional access to patients, which grow products faster. That's why you see us doing on good assets, very extensive developments, very fast, so that indication after indication we can bring to the market. That grows a product. Look at DARZALEX, IMBRUVICA, now ERLEADA, just to name a few, the next generation of TREMFYA with the six-month. We build on de-risk products also as well as on new platforms, as I indicated earlier, with the gene therapy, cell therapy, and the new assets which we brought in."),
    (3553.53, "Joaquin Duato", "Another area, Terence, where we are making significant investments is in data sciences. We are trying to embed data sciences in everything we do across R&D to both accelerate discovery and early development and also to improve late development. For example, we are using data sciences to better understand disease expression and progression and also to be more effective at molecular invention. Now we have models to accelerate molecular design of molecules for high-priority targets across all our therapeutic areas. In late development, we are also using data sciences to do a step change in the efficiency in which we run clinical trials and also to create synthetic control arms and better stratify patients. We are embedding, as I said, data sciences and making significant investments to be bilingual, both in science and in data science."),
    (3615.55, "Chris DelOrefice", "Great. Thank you, Paul and Joaquin. Thanks, Terence, for your questions. Appreciate it. Operator, next question."),
    (3623.37, "Operator", "The next question is from the line of Joanne Wuensch with BMO Capital Markets."),
    (3628.39, "Joanne Wuensch", "Good morning, everybody, thank you for taking the question. I have a specific question and then a big picture one. Specifically, you talked about 100 basis points of supply issues in medical devices. I was curious if you could share which devices were impacted and if that's been fully resolved at this stage."),
    (3646.55, "Joe Wolk", "Joanne, thanks for the question. There were two that were mentioned, obviously, our first priority is patient safety. One has been remediated, the product is actually back on the market, that's related to our circular staplers. There was a product of manufacturing lot that we pulled off the market. Again, it's been remediated and everything is back in order. The second was during a routine FDA inspection through a third-party manufacturer, which is manufacturing SURGIFLO for us. They went through the regulatory filing, identified a change in the manufacturing process, they were just seeking more information. We're working fully with the FDA, expect that to be resolved shortly."),
    (3693.8, "Joanne Wuensch", "Thank you. My big-picture question has to do with sort of the lay of the land in healthcare, how you're looking at patients, volumes, and pricing, according with that, how are tariffs impacting the business? Thank you."),
    (3708.45, "Joe Wolk", "Okay. I'll start, maybe I'll turn it over to Joaquin or Paul to give you some further insights. With respect to tariffs, first, I would say that we've had modest impact on our business. Nothing that's noteworthy. If you look specifically where most of the rhetoric and dialogue has occurred, it's been around China. Our business in China across all three of our segments has been very strong. High double-digit growth, mid-teens or higher across all three segments. We really haven't seen that impact. With respect to pricing, the pharmaceutical results, again, I think we would all agree, are very strong. That is in the face of net prices declining by 6%, similar to what we saw in 2018. In the U.S., strong growth."),
    (3758.09, "Joe Wolk", "We've got generic and biosimilar erosion, and we've got about a 6% price headwind, yet the transformational portfolio continues to deliver for patients as well as for our business results. I don't know, Joaquin, if you want to add anything around the pricing dynamic."),
    (3773.41, "Joaquin Duato", "Pricing, we see continued price erosion, which is a dynamic that we have seen in the U.S. market for the last couple of years, which we, as we have commented earlier, more than offset with our volume growth. Overall, we don't see that trend changing. What we think is that in that context, we are positioned more favorably than the rest of the companies because of three reasons. One is the diversification of our portfolio. We had in 2018, 11 medicines of more than a billion dollars. We are present across many therapeutic areas. Also with a payer mix, which is very similar to the overall market. In other words, we don't over-index in any particular payer. The second thing is that we have a very robust volume growth."),
    (3829.63, "Joaquin Duato", "This volume growth, which is driven by the share that we are gaining and the penetration through new indications, more than offsets the price erosion. Finally, we have a strong presence OUS, 45% of our sales are OUS, and in this quarter, for example, our sales OUS grew at 12.9%. Overall, we do believe that if we are able to continue to do what we do exceptionally well, which is bringing new breakthrough medicines to patients, we are very well positioned in this context of price erosion."),
    (3865.07, "Chris DelOrefice", "Great. Thank you. Thanks, Joanne, for your questions. Next question, please."),
    (3870.21, "Operator", "Next question is from Danielle Antalffy with SVB Leerink."),
    (3875.07, "Danielle Antalffy", "Hey. Good morning, guys. Thanks so much for taking the question. Just a high-level question on devices. Based on our math on a comp-adjusted basis, you saw another quarter of growth acceleration. Just wondering if you could comment on, are we past the trough now in devices, and how much of the healthy growth this quarter was J&J specific versus perhaps a sort of uplift in the various different market growth rates?"),
    (3905.37, "Joe Wolk", "Yes. Great question, Danielle. We do think that the trough is behind us with respect to medical devices. Ashley McEvoy and her team are doing a great job in terms of ensuring that across all four platforms, so eye health, cardiovascular, interventional, and orthopedics, that we've got solid plans for execution and improved performance going forward, coupled with stronger innovation. I would say, I don't have a full estimate as to what other competitors' challenges may have added to ours. We've got a ballpark estimate, I would say it was probably offset by the supply disruptions that we referenced earlier. You get back to that normalized level of, let's call it 3%-4%."),
    (3950.61, "Danielle Antalffy", "Great. That's helpful. Then just a higher-level comment on the other income upside that you're going to be reinvesting, to follow up on an earlier question. When you do need to scale back spend, given potentially lower other income as we look into 2020 and beyond, what are the levers that you can pull to do that, and in which businesses is it easiest to sort of scale back without giving up anything on the top line?"),
    (3975.19, "Joe Wolk", "Yep. We're currently looking to improve the operating margin profile within our consumer unit. A great job by Thibaut Mongon, Joaquin, in terms of really centering and focusing our investment, prioritizing that towards our strongholds of beauty skincare as well as over-the-counter medicines. And we are projected to have a strong improvement in that margin profile for this year and then going forward. I would say the same with medical devices. Once you have an improving top line, that should help the rest of the P&L, and Ashley is going about her business that way and making the right structural changes. And then lastly, in pharmaceuticals, we're already at the top of the peer set with respect to operating margin performance."),
    (4022.71, "Joe Wolk", "As that top line improves and we anniversary some of the challenges that I mentioned earlier, that should also bode well for some, I would say, incremental improvement."),
    (4032.21, "Chris DelOrefice", "Great. Thanks, Danielle. Appreciate the questions. Next question, please."),
    (4036.73, "Operator", "Next question is from Matt Miksic with Credit Suisse."),
    (4042.01, "Matt Miksic", "Thanks for taking the questions. Just one follow-up on pharma and then kind of a bigger picture question on medical devices. You talked a little bit about the XARELTO launch for CAD and PAD maybe taking some time. If you could elaborate maybe on what some of the challenges there or steps that have to take place to start gaining momentum on that front. And then I just have one follow-up."),
    (4070.13, "Joaquin Duato", "Thank you for the question, Matt. Certainly, the difference with the launches that we had in other indications like AFib and VTE is that the use of novel or anticoagulants in CAD/PAD is novel. We are establishing a new standard of care there. So far it was either aspirin, the one medicine used. Establishing a new standard of care takes longer than when you are comparing to an existing standard of care. We think that the progression will continue to be like a chronic medication, steady but constantly growing. And as I said, we are exceeding the launch align metrics of BRILINTA, and we are similar to Entresto. At this point, just to give you an idea of the extension of the use of XARELTO in CAD, PAD, we have 8,500 prescribers already."),
    (4127.03, "Joaquin Duato", "We see a steady climb, and we are confident that it will become a very important driver of growth for XARELTO."),
    (4134.39, "Matt Miksic", "That's helpful. Thank you. Maybe just on medical devices broadly, I think one of the questions we get often is just the steps that J&J can take to turn the growth up in this division. Of course, you have bright spots like Biosense Webster and CERENOVUS and others in the quarter, which you've talked about. I wonder if I could ask just what, robotic surgery is obviously an area where you've invested, continue to invest. Joe, maybe if you could sketch out the areas of med devices where you feel like there are sort of disruptive opportunities or areas where J&J can enter, expand, invest and sort of make an impact on this division."),
    (4184.13, "Joe Wolk", "Sure, Matt. Again, we are seeing improved growth rates from what we were experiencing 12 to 24 months ago. We're continuing on that right cadence, I believe. If I look at opportunities as to where we're playing, you mentioned digital surgery, that will be a growth driver going forward. I think in our interventional space, specifically around our CERENOVUS unit and stroke, it's a smaller unit that we don't report out on, but we grew about 25% in the quarter. We think that has tremendous opportunity. We do know that eye health and contact lenses specifically will be a growth driver for us based on the cadence of innovation we've got coming through there. We'll have improved performance with orthopedics."),
    (4226.77, "Joe Wolk", "We obviously had some challenges last year with respect to knee performance as we launch with Orthotaxy at some point late next year or early in 2021, as well as bring some cementless options to the marketplace, I think we'll be in very good shape where you'll see this unit performing at or above market."),
    (4251.27, "Matt Miksic", "Any things on areas that outside the company that you think about in terms of investing, not just in your businesses, but externally, like Auris?"),
    (4259.83, "Joe Wolk", "Yeah, we're always looking, Matt, across all three of our segments to fortify the portfolio that we have today. There's one or two areas that we're not currently in, but we're going to make sure that, one, we can create value when that asset is in our hands, and that we're compensating shareholders for the risk that we're bearing on their behalf. We don't just simply look at a cost of capital. There would be some risk opportunity associated with that opportunity that we want to make sure that we compensate for. I guess that's a long way of saying we're going to make sure that we pay the right value. We're not in a position where we need to do something. We'll do something when it makes sense to do it from a strategic as well as a financial perspective."),
    (4302.81, "Chris DelOrefice", "Thanks, Matt. Appreciate the questions. Operator, we have time for one last question."),
    (4307.97, "Operator", "The question will be from the line of Bob Hopkins from Bank of America."),
    (4312.95, "Bob Hopkins", "Thanks very much. Appreciate it, good morning. I'll be quick. Just two, I'll mention them both upfront. First, on the pharma side, at the beginning of the year, you guys gave guidance on the headwind from generics and biosimilars of roughly three to three and a half billion. Can you just give an update on kind of where you stand with that number today? Secondly, just a quick clarification on the talc litigation. Are you guys reserving for that currently or no? Thank you."),
    (4345.27, "Joe Wolk", "Let me take the talc question quickly. We did incur a charge in our earnings for the quarter of $190 million. That is related to defense costs only. That does not contemplate settlement or any liability payments. Again, we think we're on very firm ground with respect to the facts supporting our case. As I've mentioned on appeal, when we don't win in the original verdicts, we prevail on appeal. That's the only charge that you will see in there for the quarter, Bob."),
    (4375.69, "Joaquin Duato", "Thank you, Bob. As I said before, our growth this year is mainly driven by the strength of our core franchises. We have nine medicines growing double digit, and we see all across our franchises very strong growth. We commented on DARZALEX with 57%, IMBRUVICA 39%, STELARA 18%, TREMFYA doing very well. Overall, very positive growth in our core franchises. At the same time, we have seen less generic erosion than anticipated, mainly due to two factors. One, it's related to lower generic erosion in ZYTIGA that we anticipated, and we think that's going to increase as the year goes on, and also a delay in the introduction of a TRACLEER generic. We see now our headwind from a LOE perspective between $2.5 billion-$3 billion."),
    (4437.13, "Chris DelOrefice", "Great. Thank you, Bob. Thanks to everyone for your questions and your continued interest in our company. Apologies to those we couldn't get to because of time, don't hesitate to reach out to the investor relations team as needed. I will now turn the call back to Joe for some brief closing remarks."),
    (4452.09, "Joe Wolk", "Thanks, Chris, thanks to everyone on the call for your interest as well as your time. As you can see in today's results, not just for the quarter, but for the first half, we are well set up for both near and long-term success. We continue to manage our portfolio to benefit patients, healthcare systems, and shareholders, we will continue to invest for impact. As we anniversary some of the LOE challenges in pharmaceuticals and continue our upward momentum in our consumer health and medical device segments, we feel the business is poised for even greater success going forward. Again, thanks for your time and enjoy the rest of your day."),
    (4491.09, "Operator", "Thank you. This concludes today's Johnson & Johnson second quarter 2019 earnings conference call. You may now disconnect."),
]

paras = [{"text": text, "speakerName": speaker, "start": start} for start, speaker, text in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 61775, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)} first={paras[0]['start']}")
