# -*- coding: utf-8 -*-
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEST = REPO / "data" / "healthcare_large_cap" / "windows" / "_tmp" / "JNJ_FY2019-Q1.json"
ROWS = [
    (3210.46, "Josh Jennings", "Hi, good morning. Thanks for taking the questions. Two for Jennifer. First on esketamine, thanks for some of the details on the prepared remarks by Chris. I wonder if you could give any incremental color. I think you mentioned 475 centers already certified, first dose to a patient provided in a commercial setting. Anything else you can help share? Maybe just to start with, just as one trigger, how should we think about the centers certification ramp going over the course of 2019 and into 2020? Any other color you can share. The second question is just on cardiovascular and other. XARELTO, appreciate the details on the donut hole and the decline in Q1, there's some positive things on the horizon there, including the filing for prevention of DVT in medically ill patients."),
    (3266.08, "Josh Jennings", "Just what's the outlook there for XARELTO in terms of returning to growth? Lastly, in the same category, INVOKANA, any expectations in terms of whether the CREDENCE data can turn that franchise around? Thanks for taking the questions."),
    (3280.34, "Jennifer Taubert", "Thanks. Good morning. Yeah, we received approval and launched SPRAVATO, which is esketamine, in the first quarter, that was following the breakthrough therapy designations. It was approved for the treatment of treatment-resistant depression along with an oral antidepressant in patients who've tried two or more antidepressant therapies in that current episode. The product is also available with a REMS program as anticipated, as part of that REMS program, it requires that we do certify the sites, we also enroll patients in the REMS program prior to administration. The interest in SPRAVATO has been really high, that is across insurance plans, providers, as well as patients. Actually, a quick update. I know we spoke about the 465-center certification earlier today, I just got some new numbers. It's actually up as high as 800 sites"),
    (3340.14, "Jennifer Taubert", "That have now been certified and are approved to begin treating patients. Importantly, we've actually got a number of patients who have actually been dosed with the product and some that actually have had multiple doses successfully. We believe that we're off to a very strong start with SPRAVATO, and that it is going to be an important growth driver for us. The sites, because of the REMS program, are an important component. That's where the patients will need to go for treatment. Right now, at that number up as high as 800 sites already certified, we're well on track with our plans for the year there. Looking forward to being able to hopefully treat a large number of patients with SPRAVATO to help them with their treatment-resistant depression."),
    (3387.8, "Jennifer Taubert", "Early days, still realize that it's only been on the market a few weeks, but we're very encouraged by the signs that we're seeing. If we then move over to XARELTO. XARELTO, both TRXs and share grew in the first quarter. Unfortunately, that growth was offset by the increase in donut hole expenses that moved from 50% to 70%, and also a greater percentage of patients that were in Medicare and Medicaid, which are the most heavily discounted channels. If I give you a little bit more of the dynamics in what's going on underneath all of that and hopefully reasons for belief of success of the asset going forward."),
    (3429.12, "Jennifer Taubert", "The CAD-PAD launch is going very well, and the launch is as really consistent or even better than launch benchmarks that we had, such as products like ENTRESTO or BRILINTA, that have been proven to be very successful in the market. We've seen very positive response to the two and a half milligram vascular dose that we launched, and we do really expect this to be a significant contributor for us going forward. As a reminder, there's about 13 million patients that have CAD-PAD. While we're starting in a subset, there is extraordinary need for a product like XARELTO in patients that have CAD-PAD. Additionally, we filed for medically ill. We filed an sNDA at the end of December based on our MARINER and MAGELLAN trials, and look forward to hopefully getting approval and being able to launch that indication in the U.S. in 2019. Last on INVOKANA."),
    (3491.84, "Jennifer Taubert", "INVOKANA, we just recently reported the results of our CREDENCE study, showing that the product significantly reduces the risk of renal failure in patients with type 2 diabetes and chronic kidney disease. This is a 30% reduction of the risk of progression to end-stage kidney disease, which is things like dialysis transplant, doubling of serum creatinine or renal or cardiovascular death. Really robust results. There are also further secondary endpoints that were extraordinarily positive in that study. We plan to work with the regulators to get an indication along those lines and then to also work with payers to see if we've got the opportunity to enhance our formulary positions and get this product available for more patients. You know we've been limited because of some of the safety labeling for the product and that that's impacted it."),
    (3546.02, "Jennifer Taubert", "We're hopeful that the CREDENCE data, in bringing that forward as another opportunity for patients, will help work to try to shift that balance and perceptions around the benefit risk profile."),
    (3556.82, "Chris DelOrefice", "Great. Thanks, Josh. Appreciate the questions. Next question, please."),
    (3561.98, "Operator", "Next question comes from Geoff Meacham with Barclays."),
    (3567.34, "Geoff Meacham", "Morning, everyone. Thanks for the question. Just have a few. In PH, we're coming up on two years post the Actelion Just curious, when you think about the UPTRAVI trajectory, are there commercial drivers, say geographically or share, that are notable for the next year or so? Maybe how is that different than your original expectation? Joe, in pharma this year, you talked about the headwinds from generics and biosimilars. The new launches may take some time, though, to change the growth profile back to what you guys view as above market. At a higher level, would you view 2019 as a trough, or is there a risk that you think deceleration in pharma could persist going into 2020? Thank you."),
    (3611.34, "Jennifer Taubert", "I'll go ahead and start off on Actelion. Our total pulmonary hypertension portfolio grew by double digits in the first quarter. Increase of 15%. If you go a little bit deeper on that, together, OPSUMIT and UPTRAVI delivered over $500 million in sales, and OPSUMIT had growth of 17%, and UPTRAVI had growth of 43%. We do think that UPTRAVI is a significant driver for that business for us going forward. Also, as we anticipated when we did the deal originally, the strong growth that we're seeing with UPTRAVI is really coming from a few different areas. Continued share gains, but also greater market penetration and earlier use."),
    (3657.68, "Jennifer Taubert", "I believe as we've put our commercial capabilities across these assets, and with UPTRAVI being the newest one, we continue to get approval and get not only registration but access or reimbursement for the asset globally, which is having a lift. We're selling the product in as really the first oral PRA and really trying to drive earlier and earlier usage in the PAH treatment continuum, because we believe the best thing for patients is more aggressive treatment and earlier on in therapy. It's really showing in the results that we've seen and with that 43% growth."),
    (3695.48, "Joseph Wolk", "Great. Thanks, Jennifer. Then Geoff, to answer your second question in terms of a trough. I would say 2019 is when we would expect the largest impact from generic or biosimilar erosion. That's why we were so specific in January to outline that impact. We'll continue to see great core growth. If you look in immunology, STELARA still has market opportunities within Crohn's disease as well as some other indications. TREMFYA, most patients on psoriasis are still not treated with a biologic, so we've got a great opportunity there. Oncology will still be significant with IMBRUVICA and DARZALEX. Remember, outside the U.S., we still have ZYTIGA exclusivity, so we're in good shape there. The Actelion assets that Jennifer just referenced, and then the XARELTO indications."),
    (3744.8, "Joseph Wolk", "I would see 2019 as a trough, and once we anniversary some of these patent losses, we should be even stronger than we were in the first quarter and back to that well above market projection for pharmaceutical."),
    (3761.56, "Chris DelOrefice", "Thanks, Geoff. Appreciate the question. Next question, please."),
    (3765.74, "Operator", "The next question is from the line of Vamil Divan of Credit Suisse."),
    (3770.7, "Vamil Divan", "Hi. Great. Thanks for taking my questions. Just a couple if I could. One high-level one on pharma and following up on Chris's earlier question around rebate reform. I guess the question I'm getting, I think investors are also wondering about, is how to think about the actual list prices if the safe harbor is removed from Part D. Is it safe to assume that the list price will come down to where net prices currently are, or is it possible that list prices may end up at a higher price than where the net prices currently are in the market? Then my second question, just a specific one. I apologize if I missed this in your prepared remarks, but in terms of REMICADE and the biosimilar impact, can you just share what % of the infliximab market you still have with the brand? Thanks."),
    (3815.36, "Jennifer Taubert", "Sure. Why don't I start."),
    (3816.44, "Joseph Wolk", "We'll look that up, Vamil, as you start with the first question."),
    (3818.94, "Jennifer Taubert", "Oh, okay. I was going to say on the REMICADE one."),
    (3821.06, "Jennifer Taubert", "Okay, got it."),
    (3821.39, "Jennifer Taubert", "I've got that one."),
    (3822.12, "Joseph Wolk", "Okay, good."),
    (3823.6, "Jennifer Taubert", "We are continuing to see erosion of REMICADE, as expected. If we take a look, our team has been really competing in the marketplace to try to ensure that patients who would like to stay on REMICADE have the access and the availability to do so. Right now, we've been able to retain about 92% of the volume share for infliximab, but obviously, albeit at a lower end, very competitive price in the market. In terms of rebate reform, I think we're going to have to wait and see what ultimately is going to come forward in terms of the rebate rule. There are some options that could include patients essentially having some of that rebate flow through at the pharmacy. There's others that would require essentially, or that would involve lowering list prices going forward."),
    (3878.54, "Ashley McEvoy", "I think it's really important as you think about our business, 100% of our growth and the robust growth that we've seen, not only in this first quarter, but also last year and before, is due to volume, not due to price. However we move forward with whatever type of rebate reform, we do believe it's going to be positive for patients, help patient out-of-pocket costs, and that as Johnson & Johnson and based on our business model, we're going to be really well-poised to succeed in that environment. Again, I mentioned earlier, we're working through a number of different scenarios, and we'll have to see what ultimately comes forward. We believe that we're really well-positioned to be able to continue to succeed in that environment."),
    (3918.42, "Joseph Wolk", "Yeah, Vamil, just to put a number or two around that. Last year, our U.S. pharmaceutical business had $21 billion in discounts. We experienced net price decrease of 6.8%, yet we still had 8% growth. Unfortunately, those increased discounts aren't getting to the patients who go to the pharmacy on a monthly basis. They're experiencing elevated co-pays from what they had at least three or five years ago and even more recently. That's where the system really needs to be fixed. That should not have an impact on really how we drive our growth, and that's through innovation of unmet medical needs."),
    (3955.26, "Vamil Divan", "Okay. Thank you."),
    (3956.38, "Chris DelOrefice", "Great. Thank you, Vamil, appreciate the question. Operator, we have time for one last question."),
    (3962.4, "Operator", "Yes, sir. Next question will be coming from Jayson Bedford with Raymond James."),
    (3968.68, "Jayson Bedford", "Good morning. Thanks for taking the questions. Just a couple. On med devices, in response to an earlier question, Joe, you mentioned that you're looking for better performance going forward. Just for context, is the baseline now the one Q growth of 4.3% or is your comment related to the 3.2% growth in 2018?"),
    (3991.96, "Joseph Wolk", "Yes, I guess. I think there is a quick answer to that one, Jayson. Ashley is smiling at me. We want to see better performance. It is really benchmarked or anchored in our statement last year at our medical device and analyst day where we want to be at or above market by 2020. You have seen a consistent trajectory each and every quarter. Whether we are going to say 4.3 is now the new bar, we will have to see how the quarters play out. We are really looking at that 2020 horizon to make sure that we are at market performance or better."),
    (4022.64, "Ashley McEvoy", "I would just add, Jayson, to the question is to say, listen, quarters are not necessarily always linear. Consistent with what we did in 2018 of improving year-over-year growth acceleration, that is absolutely what we plan to achieve in 2019."),
    (4038.44, "Jayson Bedford", "Okay. That is helpful. Just on consumer, obviously a bit more of a challenging quarter. Looks like your expectation for market growth is down about 100 basis points. I appreciate the seasonal dynamics, what do you think is the source of the softness? Is it geographic in nature? Is there a price dynamic? Just a little more color there. Thanks."),
    (4060.32, "Thibaut Mongon", "Thank you for the question."),
    (4063.38, "Thibaut Mongon", "We see a deceleration in the first quarter. As I said, some of that is related to the seasonality and the structure of our portfolio. If you look at our OTC business, while we are very pleased with our performance overall for the quarter, we saw some softness due to the cold and flu season in Russia and Western Europe. If you look at beauty, we see some deceleration in the market, but we continue to outperform the market in important geographies for us, like the U.S. Baby is another category where we saw some deceleration in this winter, which affects our winter-related products. It's really seasonality. We also see some impact of de-stocking in some retailers and some geographies. I would say it's broadly based across geographies."),
    (4133.16, "Thibaut Mongon", "Having said that, we expect the softness seen in Q1 to rebound in the balance of the year to hit our projected growth for the markets where we compete of 2% for the year."),
    (4151.88, "Chris DelOrefice", "Great. Thank you, Jayson. Appreciate the question. Thanks to everyone for your questions and your continued interest in our company. Apologies to those we couldn't get to because of time, but don't hesitate to reach out to the investor relations team as needed. I did want to remind you that our pharmaceutical business review in New Brunswick is on May 15th, and we look forward to seeing all of you there. I will now turn the call back to Joseph for some brief closing remarks."),
    (4176.98, "Joseph Wolk", "Thank you, Chris, and thanks to all of you who participated in or listened to today's webcast. We hope you enjoyed the expanded management Q&A panel and that you sense the confidence we have in our 2019 outlook, which should set us up well for even better performance in 2020 and beyond. As Chris referenced, we look forward to seeing many of you at our pharmaceutical business review day. Have a great day."),
    (4200.48, "Operator", "Thank you. This concludes today's Johnson & Johnson's first quarter 2019 earnings conference call. You may now disconnect."),
]

paras = [{"text": text, "speakerName": speaker, "start": start} for start, speaker, text in ROWS]
DEST.parent.mkdir(parents=True, exist_ok=True)
DEST.write_text(json.dumps({"eventId": 61776, "isLive": False, "nextFromTimestamp": None, "paragraphs": paras}, ensure_ascii=False), encoding="utf-8")
print(f"WROTE={DEST} paras={len(paras)} first={paras[0]['start']}")
